


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE SCHEMA IF NOT EXISTS "public";


ALTER SCHEMA "public" OWNER TO "pg_database_owner";


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE OR REPLACE FUNCTION "public"."handle_new_user"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$
BEGIN
  INSERT INTO public.profiles (
    user_id,
    user_name,
    email,
    avatar_path
  )
  VALUES (
    new.id,
    -- user_name: display_name ?곗꽑 留ㅽ븨
    COALESCE(
      new.raw_user_meta_data->>'display_name',
      new.raw_user_meta_data->>'full_name',
      new.raw_user_meta_data->>'name',
      NULL
    ),
    -- email: 媛???대찓??
    COALESCE(new.email, NULL),
    -- avatar_path: ?뚯뀥 ?꾨줈???대?吏 URL 留ㅽ븨 (?놁쑝硫?NULL)
    COALESCE(
      new.raw_user_meta_data->>'avatar_url',
      new.raw_user_meta_data->>'picture',
      NULL
    )
  );
  RETURN new;
END;
$$;


ALTER FUNCTION "public"."handle_new_user"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."increment_portfolio_view"("p_project_id" "uuid") RETURNS "void"
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$begin
  update public.portfolios
  set view_count = coalesce(view_count, 0) + 1
  where project_id = p_project_id;
end;$$;


ALTER FUNCTION "public"."increment_portfolio_view"("p_project_id" "uuid") OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."increment_profile_view"("p_user_id" "uuid") RETURNS "void"
    LANGUAGE "sql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
  update public.profiles
  set profile_view = coalesce(profile_view, 0) + 1
  where user_id = p_user_id;
$$;


ALTER FUNCTION "public"."increment_profile_view"("p_user_id" "uuid") OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."set_updated_at"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
begin
  new.updated_at = now();
  return new;
end;
$$;


ALTER FUNCTION "public"."set_updated_at"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."sync_likes_count"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$
BEGIN
  IF (tg_op = 'INSERT') THEN
    UPDATE portfolios SET likes_count = coalesce(likes_count, 0) + 1
    WHERE project_id = new.project_id;
  ELSIF (tg_op = 'DELETE') THEN
    UPDATE portfolios SET likes_count = coalesce(likes_count, 0) - 1
    WHERE project_id = old.project_id;
  END IF;
  RETURN null;
END;
$$;


ALTER FUNCTION "public"."sync_likes_count"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."ai_action_cooldowns" (
    "user_id" "uuid" NOT NULL,
    "action" "text" NOT NULL,
    "last_requested_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "repository_url" "text" DEFAULT ''::"text" NOT NULL,
    CONSTRAINT "ai_action_cooldowns_action_check" CHECK (("action" = ANY (ARRAY['analyze'::"text", 'draft'::"text"])))
);


ALTER TABLE "public"."ai_action_cooldowns" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."bookmarks" (
    "bookmark_id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "project_id" "uuid" NOT NULL,
    "collection_id" "uuid",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."bookmarks" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."collections" (
    "collection_id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "owner_id" "uuid" NOT NULL,
    "title" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."collections" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."messages" (
    "id" bigint NOT NULL,
    "sender_id" "uuid" NOT NULL,
    "receiver_id" "uuid",
    "content" "text" NOT NULL,
    "is_read" boolean DEFAULT false,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."messages" OWNER TO "postgres";


ALTER TABLE "public"."messages" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."messages_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."portfolio_ai_created" (
    "project_id" "uuid" NOT NULL,
    "project_summary" "text",
    "main_features" "text",
    "technical_features" "text",
    "project_structure" "text",
    "analyzed_role" "text",
    "participation_details" "text",
    "analysis_limitation" "text",
    "analysis_evidence" "jsonb",
    "github_analyzed_at" timestamp with time zone,
    "draft_source_content" "text",
    "generated_content" "text",
    "ai_short_summary" "text",
    "draft_generated_at" timestamp with time zone
);


ALTER TABLE "public"."portfolio_ai_created" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."portfolio_categories" (
    "project_id" "uuid" NOT NULL,
    "category" "text" NOT NULL
);


ALTER TABLE "public"."portfolio_categories" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."portfolio_images" (
    "image_id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "project_id" "uuid" NOT NULL,
    "image_path" "text" NOT NULL,
    "display_order" integer,
    "is_thumbnail" boolean DEFAULT false NOT NULL,
    "alt_text" "text",
    CONSTRAINT "portfolio_images_display_order_check" CHECK ((("display_order" IS NULL) OR ("display_order" >= 0)))
);


ALTER TABLE "public"."portfolio_images" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."portfolio_likes" (
    "project_id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."portfolio_likes" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."portfolio_tech_stacks" (
    "project_id" "uuid" NOT NULL,
    "tech_stack" "text" NOT NULL
);


ALTER TABLE "public"."portfolio_tech_stacks" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."portfolios" (
    "project_id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "author_id" "uuid" NOT NULL,
    "title" "text" NOT NULL,
    "summary" "text",
    "description" "text" NOT NULL,
    "started_at" "date" DEFAULT CURRENT_DATE,
    "ended_at" "date" DEFAULT CURRENT_DATE,
    "project_type" "text",
    "team_size" "text",
    "author_role" "text",
    "environment" "text",
    "deploy_url" "text",
    "repository_url" "text",
    "is_public" boolean DEFAULT true NOT NULL,
    "view_count" bigint DEFAULT 0 NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "likes_count" bigint DEFAULT 0,
    CONSTRAINT "portfolios_check" CHECK ((("ended_at" IS NULL) OR ("started_at" IS NULL) OR ("ended_at" >= "started_at"))),
    CONSTRAINT "portfolios_description_check" CHECK (("char_length"(TRIM(BOTH FROM "description")) > 0)),
    CONSTRAINT "portfolios_team_size_check" CHECK ((("team_size" IS NULL) OR ("team_size" = ANY (ARRAY['solo'::"text", 'small-team'::"text", 'medium-team'::"text", 'department'::"text", 'large-org'::"text", 'large-community'::"text", 'unknown'::"text"])))),
    CONSTRAINT "portfolios_title_check" CHECK (("char_length"(TRIM(BOTH FROM "title")) > 0)),
    CONSTRAINT "portfolios_view_count_check" CHECK (("view_count" >= 0))
);


ALTER TABLE "public"."portfolios" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."profiles" (
    "user_id" "uuid" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "avatar_path" "text",
    "user_name" "text" NOT NULL,
    "user_category" "text",
    "skills" "text"[],
    "bio" "text",
    "email" "text",
    "is_public" boolean DEFAULT false NOT NULL,
    "github_url" "text",
    "profile_view" bigint DEFAULT 0 NOT NULL,
    "url2" "text",
    CONSTRAINT "profiles_contact_email_check" CHECK ((("email" IS NULL) OR ("email" ~* '^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$'::"text"))),
    CONSTRAINT "profiles_github_url_check" CHECK ((("github_url" IS NULL) OR ("github_url" ~* '^https://(www\.)?github\.com/'::"text"))),
    CONSTRAINT "profiles_profile_view_check" CHECK (("profile_view" >= 0)),
    CONSTRAINT "profiles_user_name_check" CHECK (("char_length"(TRIM(BOTH FROM "user_name")) > 0))
);


ALTER TABLE "public"."profiles" OWNER TO "postgres";


ALTER TABLE ONLY "public"."ai_action_cooldowns"
    ADD CONSTRAINT "ai_action_cooldowns_pkey" PRIMARY KEY ("user_id", "action", "repository_url");



ALTER TABLE ONLY "public"."portfolio_ai_created"
    ADD CONSTRAINT "ai_created_pkey" PRIMARY KEY ("project_id");



ALTER TABLE ONLY "public"."bookmarks"
    ADD CONSTRAINT "bookmarks_pkey" PRIMARY KEY ("bookmark_id");



ALTER TABLE ONLY "public"."bookmarks"
    ADD CONSTRAINT "bookmarks_unique" UNIQUE ("user_id", "project_id", "collection_id");



ALTER TABLE ONLY "public"."collections"
    ADD CONSTRAINT "collections_pkey" PRIMARY KEY ("collection_id");



ALTER TABLE ONLY "public"."portfolio_likes"
    ADD CONSTRAINT "likes_pkey" PRIMARY KEY ("project_id", "user_id");



ALTER TABLE ONLY "public"."messages"
    ADD CONSTRAINT "messages_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."portfolio_categories"
    ADD CONSTRAINT "portfolio_categories_pkey" PRIMARY KEY ("project_id", "category");



ALTER TABLE ONLY "public"."portfolio_images"
    ADD CONSTRAINT "portfolio_images_pkey" PRIMARY KEY ("image_id");



ALTER TABLE ONLY "public"."portfolio_tech_stacks"
    ADD CONSTRAINT "portfolio_tech_stacks_pkey" PRIMARY KEY ("project_id", "tech_stack");



ALTER TABLE ONLY "public"."portfolios"
    ADD CONSTRAINT "portfolios_pkey" PRIMARY KEY ("project_id");



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_pkey" PRIMARY KEY ("user_id");



CREATE INDEX "messages_receiver_id_idx" ON "public"."messages" USING "btree" ("receiver_id");



CREATE INDEX "messages_sender_id_idx" ON "public"."messages" USING "btree" ("sender_id");



CREATE UNIQUE INDEX "portfolio_images_one_thumbnail_per_project" ON "public"."portfolio_images" USING "btree" ("project_id") WHERE ("is_thumbnail" = true);



CREATE OR REPLACE TRIGGER "portfolio_likes_count_trigger" AFTER INSERT OR DELETE ON "public"."portfolio_likes" FOR EACH ROW EXECUTE FUNCTION "public"."sync_likes_count"();



CREATE OR REPLACE TRIGGER "portfolios_set_updated_at" BEFORE UPDATE ON "public"."portfolios" FOR EACH ROW EXECUTE FUNCTION "public"."set_updated_at"();



ALTER TABLE ONLY "public"."ai_action_cooldowns"
    ADD CONSTRAINT "ai_action_cooldowns_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."portfolio_ai_created"
    ADD CONSTRAINT "ai_created_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "public"."portfolios"("project_id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."bookmarks"
    ADD CONSTRAINT "bookmarks_collection_id_fkey" FOREIGN KEY ("collection_id") REFERENCES "public"."collections"("collection_id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."bookmarks"
    ADD CONSTRAINT "bookmarks_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "public"."portfolios"("project_id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."bookmarks"
    ADD CONSTRAINT "bookmarks_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."profiles"("user_id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."collections"
    ADD CONSTRAINT "collections_owner_id_fkey" FOREIGN KEY ("owner_id") REFERENCES "public"."profiles"("user_id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."portfolio_likes"
    ADD CONSTRAINT "likes_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "public"."portfolios"("project_id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."portfolio_likes"
    ADD CONSTRAINT "likes_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."profiles"("user_id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."messages"
    ADD CONSTRAINT "messages_receiver_id_fkey" FOREIGN KEY ("receiver_id") REFERENCES "public"."profiles"("user_id");



ALTER TABLE ONLY "public"."messages"
    ADD CONSTRAINT "messages_sender_id_fkey" FOREIGN KEY ("sender_id") REFERENCES "public"."profiles"("user_id");



ALTER TABLE ONLY "public"."portfolio_categories"
    ADD CONSTRAINT "portfolio_categories_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "public"."portfolios"("project_id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."portfolio_images"
    ADD CONSTRAINT "portfolio_images_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "public"."portfolios"("project_id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."portfolio_tech_stacks"
    ADD CONSTRAINT "portfolio_tech_stacks_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "public"."portfolios"("project_id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."portfolios"
    ADD CONSTRAINT "portfolios_author_id_fkey" FOREIGN KEY ("author_id") REFERENCES "public"."profiles"("user_id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



CREATE POLICY "Authors can update their own portfolio" ON "public"."portfolios" FOR UPDATE TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "author_id")) WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "author_id"));



CREATE POLICY "Enable delete for users based on author_id" ON "public"."portfolios" FOR DELETE TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "author_id"));



CREATE POLICY "Enable delete for users based on user_id" ON "public"."portfolio_likes" FOR DELETE USING ((( SELECT "auth"."uid"() AS "uid") = "user_id"));



CREATE POLICY "Enable insert for authenticated users only" ON "public"."portfolio_likes" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "Enable insert for users" ON "public"."profiles" FOR INSERT TO "authenticated", "anon" WITH CHECK (true);



CREATE POLICY "Enable read access for all users" ON "public"."portfolio_likes" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."profiles" FOR SELECT USING (true);



CREATE POLICY "Message participants can delete messages" ON "public"."messages" FOR DELETE TO "authenticated" USING (((( SELECT "auth"."uid"() AS "uid") = "sender_id") OR (( SELECT "auth"."uid"() AS "uid") = "receiver_id")));



CREATE POLICY "Message participants can update messages" ON "public"."messages" FOR UPDATE TO "authenticated" USING (((( SELECT "auth"."uid"() AS "uid") = "sender_id") OR (( SELECT "auth"."uid"() AS "uid") = "receiver_id"))) WITH CHECK (((( SELECT "auth"."uid"() AS "uid") = "sender_id") OR (( SELECT "auth"."uid"() AS "uid") = "receiver_id")));



CREATE POLICY "Policy with table joins" ON "public"."profiles" FOR UPDATE TO "authenticated" USING (("auth"."uid"() = "user_id")) WITH CHECK (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can create their own bookmarks" ON "public"."bookmarks" FOR INSERT TO "authenticated" WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "user_id"));



CREATE POLICY "Users can create their own collections" ON "public"."collections" FOR INSERT TO "authenticated" WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "owner_id"));



CREATE POLICY "Users can delete own portfolio categories" ON "public"."portfolio_categories" FOR DELETE TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."portfolios"
  WHERE (("portfolios"."project_id" = "portfolio_categories"."project_id") AND ("portfolios"."author_id" = ( SELECT "auth"."uid"() AS "uid"))))));



CREATE POLICY "Users can delete own portfolio tech stacks" ON "public"."portfolio_tech_stacks" FOR DELETE TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."portfolios"
  WHERE (("portfolios"."project_id" = "portfolio_tech_stacks"."project_id") AND ("portfolios"."author_id" = ( SELECT "auth"."uid"() AS "uid"))))));



CREATE POLICY "Users can delete their own bookmarks" ON "public"."bookmarks" FOR DELETE TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "user_id"));



CREATE POLICY "Users can delete their own collections" ON "public"."collections" FOR DELETE TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "owner_id"));



CREATE POLICY "Users can insert own portfolio" ON "public"."portfolios" FOR INSERT TO "authenticated" WITH CHECK (("author_id" = ( SELECT "auth"."uid"() AS "uid")));



CREATE POLICY "Users can insert own portfolio ai data" ON "public"."portfolio_ai_created" FOR INSERT TO "authenticated" WITH CHECK ((EXISTS ( SELECT 1
   FROM "public"."portfolios"
  WHERE (("portfolios"."project_id" = "portfolio_ai_created"."project_id") AND ("portfolios"."author_id" = ( SELECT "auth"."uid"() AS "uid"))))));



CREATE POLICY "Users can insert own portfolio categories" ON "public"."portfolio_categories" FOR INSERT TO "authenticated" WITH CHECK ((EXISTS ( SELECT 1
   FROM "public"."portfolios"
  WHERE (("portfolios"."project_id" = "portfolio_categories"."project_id") AND ("portfolios"."author_id" = ( SELECT "auth"."uid"() AS "uid"))))));



CREATE POLICY "Users can insert own portfolio images" ON "public"."portfolio_images" FOR INSERT TO "authenticated" WITH CHECK ((EXISTS ( SELECT 1
   FROM "public"."portfolios"
  WHERE (("portfolios"."project_id" = "portfolio_images"."project_id") AND ("portfolios"."author_id" = ( SELECT "auth"."uid"() AS "uid"))))));



CREATE POLICY "Users can insert own portfolio tech stacks" ON "public"."portfolio_tech_stacks" FOR INSERT TO "authenticated" WITH CHECK ((EXISTS ( SELECT 1
   FROM "public"."portfolios"
  WHERE (("portfolios"."project_id" = "portfolio_tech_stacks"."project_id") AND ("portfolios"."author_id" = ( SELECT "auth"."uid"() AS "uid"))))));



CREATE POLICY "Users can send messages" ON "public"."messages" FOR INSERT TO "authenticated" WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "sender_id"));



CREATE POLICY "Users can update own portfolio ai data" ON "public"."portfolio_ai_created" FOR UPDATE TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."portfolios"
  WHERE (("portfolios"."project_id" = "portfolio_ai_created"."project_id") AND ("portfolios"."author_id" = ( SELECT "auth"."uid"() AS "uid")))))) WITH CHECK ((EXISTS ( SELECT 1
   FROM "public"."portfolios"
  WHERE (("portfolios"."project_id" = "portfolio_ai_created"."project_id") AND ("portfolios"."author_id" = ( SELECT "auth"."uid"() AS "uid"))))));



CREATE POLICY "Users can update their own collections" ON "public"."collections" FOR UPDATE TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "owner_id")) WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "owner_id"));



CREATE POLICY "Users can view their messages" ON "public"."messages" FOR SELECT TO "authenticated" USING (((( SELECT "auth"."uid"() AS "uid") = "sender_id") OR (( SELECT "auth"."uid"() AS "uid") = "receiver_id")));



CREATE POLICY "Users can view their own bookmarks" ON "public"."bookmarks" FOR SELECT TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "user_id"));



CREATE POLICY "Users can view their own collections" ON "public"."collections" FOR SELECT TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "owner_id"));



ALTER TABLE "public"."ai_action_cooldowns" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "ai_action_cooldowns_insert_own" ON "public"."ai_action_cooldowns" FOR INSERT WITH CHECK (("auth"."uid"() = "user_id"));



CREATE POLICY "ai_action_cooldowns_select_own" ON "public"."ai_action_cooldowns" FOR SELECT USING (("auth"."uid"() = "user_id"));



CREATE POLICY "ai_action_cooldowns_update_own" ON "public"."ai_action_cooldowns" FOR UPDATE USING (("auth"."uid"() = "user_id"));



ALTER TABLE "public"."bookmarks" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."collections" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."messages" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."portfolio_ai_created" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "portfolio_ai_created_delete_author" ON "public"."portfolio_ai_created" FOR DELETE TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."portfolios" "p"
  WHERE (("p"."project_id" = "portfolio_ai_created"."project_id") AND ("p"."author_id" = ( SELECT "auth"."uid"() AS "uid"))))));



CREATE POLICY "portfolio_ai_created_select_public_or_own" ON "public"."portfolio_ai_created" FOR SELECT TO "authenticated", "anon" USING ((EXISTS ( SELECT 1
   FROM "public"."portfolios" "p"
  WHERE (("p"."project_id" = "portfolio_ai_created"."project_id") AND (("p"."is_public" = true) OR ("p"."author_id" = ( SELECT "auth"."uid"() AS "uid")))))));



ALTER TABLE "public"."portfolio_categories" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "portfolio_categories_select_public_or_own" ON "public"."portfolio_categories" FOR SELECT TO "authenticated", "anon" USING ((EXISTS ( SELECT 1
   FROM "public"."portfolios" "p"
  WHERE (("p"."project_id" = "portfolio_categories"."project_id") AND (("p"."is_public" = true) OR ("p"."author_id" = ( SELECT "auth"."uid"() AS "uid")))))));



ALTER TABLE "public"."portfolio_images" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "portfolio_images_delete_own" ON "public"."portfolio_images" FOR DELETE USING ((EXISTS ( SELECT 1
   FROM "public"."portfolios"
  WHERE (("portfolios"."project_id" = "portfolio_images"."project_id") AND ("portfolios"."author_id" = "auth"."uid"())))));



CREATE POLICY "portfolio_images_select_public_or_own" ON "public"."portfolio_images" FOR SELECT TO "authenticated", "anon" USING ((EXISTS ( SELECT 1
   FROM "public"."portfolios" "p"
  WHERE (("p"."project_id" = "portfolio_images"."project_id") AND (("p"."is_public" = true) OR ("p"."author_id" = ( SELECT "auth"."uid"() AS "uid")))))));



ALTER TABLE "public"."portfolio_likes" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."portfolio_tech_stacks" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "portfolio_tech_stacks_select_public_or_own" ON "public"."portfolio_tech_stacks" FOR SELECT TO "authenticated", "anon" USING ((EXISTS ( SELECT 1
   FROM "public"."portfolios" "p"
  WHERE (("p"."project_id" = "portfolio_tech_stacks"."project_id") AND (("p"."is_public" = true) OR ("p"."author_id" = ( SELECT "auth"."uid"() AS "uid")))))));



ALTER TABLE "public"."portfolios" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "portfolios_select_public_or_own" ON "public"."portfolios" FOR SELECT TO "authenticated", "anon" USING ((("is_public" = true) OR ("author_id" = ( SELECT "auth"."uid"() AS "uid"))));



ALTER TABLE "public"."profiles" ENABLE ROW LEVEL SECURITY;


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";



GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "anon";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "service_role";



GRANT ALL ON FUNCTION "public"."increment_portfolio_view"("p_project_id" "uuid") TO "anon";
GRANT ALL ON FUNCTION "public"."increment_portfolio_view"("p_project_id" "uuid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."increment_portfolio_view"("p_project_id" "uuid") TO "service_role";



GRANT ALL ON FUNCTION "public"."increment_profile_view"("p_user_id" "uuid") TO "anon";
GRANT ALL ON FUNCTION "public"."increment_profile_view"("p_user_id" "uuid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."increment_profile_view"("p_user_id" "uuid") TO "service_role";



GRANT ALL ON FUNCTION "public"."set_updated_at"() TO "anon";
GRANT ALL ON FUNCTION "public"."set_updated_at"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."set_updated_at"() TO "service_role";



GRANT ALL ON FUNCTION "public"."sync_likes_count"() TO "anon";
GRANT ALL ON FUNCTION "public"."sync_likes_count"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."sync_likes_count"() TO "service_role";



GRANT ALL ON TABLE "public"."ai_action_cooldowns" TO "anon";
GRANT ALL ON TABLE "public"."ai_action_cooldowns" TO "authenticated";
GRANT ALL ON TABLE "public"."ai_action_cooldowns" TO "service_role";



GRANT ALL ON TABLE "public"."bookmarks" TO "anon";
GRANT ALL ON TABLE "public"."bookmarks" TO "authenticated";
GRANT ALL ON TABLE "public"."bookmarks" TO "service_role";



GRANT ALL ON TABLE "public"."collections" TO "anon";
GRANT ALL ON TABLE "public"."collections" TO "authenticated";
GRANT ALL ON TABLE "public"."collections" TO "service_role";



GRANT ALL ON TABLE "public"."messages" TO "anon";
GRANT ALL ON TABLE "public"."messages" TO "authenticated";
GRANT ALL ON TABLE "public"."messages" TO "service_role";



GRANT ALL ON SEQUENCE "public"."messages_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."messages_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."messages_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."portfolio_ai_created" TO "anon";
GRANT ALL ON TABLE "public"."portfolio_ai_created" TO "authenticated";
GRANT ALL ON TABLE "public"."portfolio_ai_created" TO "service_role";



GRANT ALL ON TABLE "public"."portfolio_categories" TO "anon";
GRANT ALL ON TABLE "public"."portfolio_categories" TO "authenticated";
GRANT ALL ON TABLE "public"."portfolio_categories" TO "service_role";



GRANT ALL ON TABLE "public"."portfolio_images" TO "anon";
GRANT ALL ON TABLE "public"."portfolio_images" TO "authenticated";
GRANT ALL ON TABLE "public"."portfolio_images" TO "service_role";



GRANT ALL ON TABLE "public"."portfolio_likes" TO "anon";
GRANT ALL ON TABLE "public"."portfolio_likes" TO "authenticated";
GRANT ALL ON TABLE "public"."portfolio_likes" TO "service_role";



GRANT ALL ON TABLE "public"."portfolio_tech_stacks" TO "anon";
GRANT ALL ON TABLE "public"."portfolio_tech_stacks" TO "authenticated";
GRANT ALL ON TABLE "public"."portfolio_tech_stacks" TO "service_role";



GRANT ALL ON TABLE "public"."portfolios" TO "anon";
GRANT ALL ON TABLE "public"."portfolios" TO "authenticated";
GRANT ALL ON TABLE "public"."portfolios" TO "service_role";



GRANT UPDATE("title") ON TABLE "public"."portfolios" TO "authenticated";



GRANT UPDATE("summary") ON TABLE "public"."portfolios" TO "authenticated";



GRANT UPDATE("description") ON TABLE "public"."portfolios" TO "authenticated";



GRANT UPDATE("started_at") ON TABLE "public"."portfolios" TO "authenticated";



GRANT UPDATE("ended_at") ON TABLE "public"."portfolios" TO "authenticated";



GRANT UPDATE("project_type") ON TABLE "public"."portfolios" TO "authenticated";



GRANT UPDATE("team_size") ON TABLE "public"."portfolios" TO "authenticated";



GRANT UPDATE("author_role") ON TABLE "public"."portfolios" TO "authenticated";



GRANT UPDATE("environment") ON TABLE "public"."portfolios" TO "authenticated";



GRANT UPDATE("deploy_url") ON TABLE "public"."portfolios" TO "authenticated";



GRANT UPDATE("repository_url") ON TABLE "public"."portfolios" TO "authenticated";



GRANT UPDATE("is_public") ON TABLE "public"."portfolios" TO "authenticated";



GRANT UPDATE("view_count") ON TABLE "public"."portfolios" TO "anon";
GRANT UPDATE("view_count") ON TABLE "public"."portfolios" TO "authenticated";



GRANT ALL ON TABLE "public"."profiles" TO "anon";
GRANT ALL ON TABLE "public"."profiles" TO "authenticated";
GRANT ALL ON TABLE "public"."profiles" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";







